// Constant Variables
var SPREAD_SHEET_ID = ""
var UPDATE_SIGNIN_STATUS = 'UPDATE_SIGNIN_STATUS';
var GET_SHEET_ROWS = 'GET_SHEET_ROWS';
var ADD_VISIT = 'ADD_VISIT';
var UPDATE_NOTE = 'UPDATE_NOTE';
var HIDE_PERSON = 'HIDE_PERSON';
var MAP_READY = 'MAP_READY';
var POPULATE_MAP = 'POPULATE_MAP';
var SWITCH_DISPLAY_MODE = 'SWITCH_DISPLAY_MODE';
var FILTER_PEOPLE = 'FILTER_PEOPLE';
var DISPLAY_MODE = {MAP: 'map', LIST: 'list'};